name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'gifs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
          - snapshot
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1.1.1
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-cask@master

      - name: Run tests
        run: make test
